### ISSUE TITLE
Feature Request: Automate the verified client deals

### ISSUE THREAD

**Issue by William8Work** [nebulaai/swan#12]
**Use Case**
as a miner, I would like to automate the verified client deal making process so that it can run after my initial approval.

**Descriptions and Steps**
It would be great if the tool can do the following things:
1). Run as systemd daemon services (or I can set it up to run)
2). Listen to new deals coming available through swan site
3). Fetch the CID, and downloads the car file
4). Once the download completes, run the lotus-miner storage-deals import-data to start the sealing process.
5). Updates swan site on the sealing status. and marks success when the sealing is done.
6:40
so that I can leave the process to it without manual steps :slightly_smiling_face:

Additional considerations
1). Provide a step to allow the miner approve or reject a deal, or set an agreed price with a specific client so that I don't need to keep changing the ask-price for the same client
2). Provide a default max number of deals for a specific client under that price so that I don't need to approve every time when the same client proposing the same price. But the default max number of deals allows a level of protection for the miner.

**Comment by flyworker** [comment]
We design it as the following steps:
Get API token and keys from Swan website
* Swan miner listening to Accepted/Assigned Task list?
* Download using aria2 with config
* Start sealing.
* Update APIs for deal status

**Comment by William8Work** [comment]
Sounds great. Can't wait to try it out!!

**Comment by flyworker** [comment]
@William8Work It is working now with the master branch.
