### ISSUE TITLE
When download CSV from a task swan show 15 files   but the csv only 11 line

### ISSUE THREAD

**Issue by flyworker** [nebulaai/swan#18]
**Describe the bug**
When download CSV swan show 15 files   but the csv only 11 line

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by czhang-nbai** [comment]
test passed,  to download at 'BROWSE TASKS', 'MY TASK' -> 'As Client', 'MY TASK' -> 'As Miner'
