### ISSUE TITLE
Error displayed when putting task in complete status

### ISSUE THREAD

**Issue by gh3990** [nebulaai/swan#24]
**Describe the bug**
Error displayed when putting task in complete status

**To Reproduce**
1. Go to task details
2. Click on Action - 3 dots
3. Select mark as completed

![image](https://user-images.githubusercontent.com/70083964/107863411-886bb380-6e54-11eb-9a75-5ca69a4f8d4b.png)

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/70083964/107863397-68d48b00-6e54-11eb-8bc3-afc13dc6d92c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 10
 - Browser [e.g. chrome, safari] - Chrome
 - Version [e.g. 22] - latest

**Comment by flyworker** [comment]
turns out it is a bug on server side, note should be optional
