### ISSUE TITLE
Miner storage deals get-ask not updated

### ISSUE THREAD

**Issue by William8Work** [nebulaai/swan#8]
Issues

I saw my miner is listed in the site showing the deals details. It's great. However, after I updated my miner through storage-deals set-ask, then after 2-3 hours later, come back to this site, the details are not refreshed.

Expected Result
After I update the storage-deals set-ask to the miner, the data should be populated into the swan dashboard with reasonable timing. Or, show a "refresh" button under my task, or miner management, so that I can refresh manually.

**Comment by flyworker** [comment]
Is this one fixed? miner id?
