### ISSUE TITLE
Password reset, spinning circle

### ISSUE THREAD

**Issue by cwhiggins** [nebulaai/swan#9]
I guess I registered, don't remember when. I don't remember password, tried to reset, but just sits there, spinning circle.

**Comment by flyworker** [comment]
Yes, the feature is not implemented, need to be done

**Comment by flyworker** [comment]
It should be resolved.

**Comment by cwhiggins** [comment]
Sorry, just tried it and get an error message. which browser would you recommend be used with filswan? I was using Firefox

**Comment by flyworker** [comment]
which step failed? Did not get the reset link or get the link but cannot reset?

**Comment by czhang-nbai** [comment]
> Sorry, just tried it and get an error message. which browser would you recommend be used with filswan? I was using Firefox

Sorry for the inconvenience. We were deploying a fix at that time spot. Please try again and it should work fine now.

**Comment by flyworker** [comment]
Closed as no further report.
